/** Default seed data matching supabase/telematics.sql */

export const SEED_SCORES = [
  {
    driver_id: "driver_001",
    score: 82,
    percentile: 91,
    grade: "A",
    trips_analyzed: 847,
    miles_analyzed: 12483,
    speed_compliance: 88,
    smooth_braking: 79,
    smooth_acceleration: 84,
    phone_usage: 95,
    night_driving_safety: 76,
  },
  {
    driver_id: "driver_002",
    score: 91,
    percentile: 97,
    grade: "A+",
    trips_analyzed: 1203,
    miles_analyzed: 18920,
    speed_compliance: 95,
    smooth_braking: 92,
    smooth_acceleration: 89,
    phone_usage: 98,
    night_driving_safety: 88,
  },
  {
    driver_id: "driver_003",
    score: 67,
    percentile: 72,
    grade: "B",
    trips_analyzed: 634,
    miles_analyzed: 9847,
    speed_compliance: 72,
    smooth_braking: 65,
    smooth_acceleration: 70,
    phone_usage: 88,
    night_driving_safety: 61,
  },
  {
    driver_id: "driver_004",
    score: 78,
    percentile: 85,
    grade: "B+",
    trips_analyzed: 921,
    miles_analyzed: 14230,
    speed_compliance: 82,
    smooth_braking: 76,
    smooth_acceleration: 80,
    phone_usage: 91,
    night_driving_safety: 73,
  },
  {
    driver_id: "driver_005",
    score: 55,
    percentile: 58,
    grade: "C+",
    trips_analyzed: 412,
    miles_analyzed: 6120,
    speed_compliance: 61,
    smooth_braking: 52,
    smooth_acceleration: 58,
    phone_usage: 79,
    night_driving_safety: 49,
  },
  {
    driver_id: "driver_006",
    score: 88,
    percentile: 94,
    grade: "A",
    trips_analyzed: 1089,
    miles_analyzed: 16340,
    speed_compliance: 91,
    smooth_braking: 86,
    smooth_acceleration: 88,
    phone_usage: 96,
    night_driving_safety: 83,
  },
  {
    driver_id: "driver_007",
    score: 94,
    percentile: 99,
    grade: "A+",
    trips_analyzed: 1456,
    miles_analyzed: 21780,
    speed_compliance: 97,
    smooth_braking: 95,
    smooth_acceleration: 93,
    phone_usage: 99,
    night_driving_safety: 91,
  },
  {
    driver_id: "driver_008",
    score: 71,
    percentile: 78,
    grade: "B",
    trips_analyzed: 756,
    miles_analyzed: 11230,
    speed_compliance: 75,
    smooth_braking: 69,
    smooth_acceleration: 73,
    phone_usage: 87,
    night_driving_safety: 66,
  },
  {
    driver_id: "driver_009",
    score: 63,
    percentile: 68,
    grade: "B-",
    trips_analyzed: 523,
    miles_analyzed: 7840,
    speed_compliance: 68,
    smooth_braking: 61,
    smooth_acceleration: 65,
    phone_usage: 83,
    night_driving_safety: 58,
  },
  {
    driver_id: "driver_010",
    score: 45,
    percentile: 42,
    grade: "D",
    trips_analyzed: 289,
    miles_analyzed: 4320,
    speed_compliance: 51,
    smooth_braking: 43,
    smooth_acceleration: 47,
    phone_usage: 71,
    night_driving_safety: 38,
  },
];

export const MIXED_SCENARIO_SCORES = [92, 85, 72, 65, 58, 88, 95, 78, 62, 48];

export const DEGRADATION_DRIVERS = ["driver_003", "driver_005", "driver_008"];

export const SANDBOX_DRIVER_IDS = SEED_SCORES.map((s) => s.driver_id);
